### ISSUE TITLE
Поиск по нативном дереву (Карпова, Черноус)

### ISSUE THREAD

**Issue by tshemsedinov** [HowProgrammingWorks/TreeNode#4]
Пример нативного дерева тут:
https://github.com/HowProgrammingWorks/TreeNode/blob/master/JavaScript/3-native.js
```js
let tree = {
  n3: [1, 2, 3],
  n1: { n11: { name: 'Fish' }, n12: { name: 'Bird' }, n13: { name: 'Dog' } },
  n2: { n21: { name: 'Horse' }, n22: { name: 'Mouse' } },
  n3: { name: 'Developer', hands: 2 }
};

// Карпова
// search(trre, query); // result: node (первый подходящий)
search(trre, { name: 'Mouse' });
search(trre, { name: 'Developer', hands: 2 });

// Черноус
// find(trre, nodeType, [nodeName]); // result: node (первый подходящий)
find(trre, 'object');
find(trre, 'object', 'n3');
```
@karpusik @sweetkaterina

**Comment by Karpusik** [comment]
function isEqual(obj1,obj2){ 

	for(let key in obj1){ 
		if(obj1[key]!=obj2[key])return false; 

	} 
	return true; 
		} 
		
//рекурсивно проходим по дереву, если находим равный объект возвращаем его 
function search(tree, query){ 

	for(let node in tree){ 
		if( typeof tree[node] === 'object'){ 

			if(isEqual(tree[node],query))return tree[node]; 

			var res = search(tree[node],query); 
		if(res)return res; 
		} 
	} 
}

**Comment by Sweetkaterina** [comment]
> рекурсивно проходим по дереву, если находим совпадающий объект возвращаем


```
function find(tree, query, nodeName){
	
	for(let node in tree){
		if( typeof tree[node] === 'object'){
			
			if(!nodeName)return tree[node];
			else if(node==nodeName)return tree[node];
			
			var res = find(tree[node], query, nodeName);
			if(res)return res;
		}
	}
}
```

**Comment by tshemsedinov** [comment]
* Стиль кода: https://learn.javascript.ru/coding-style
* Делайте коммиты в исходники, а не сюда
